Add missing env var
googleapis/google-auth-library-python pull request #1518
Opened 2024-04-12 20:54 UTC by ludoch

2024-04-13 22:09 UTC, arithmetic1728 requested changes
Thank you for the pull request!

Could you add a `chore:` prefix to your commit message like `chore: make metadata...`?

There are also a few kokoro build failures.
(1) `lint` failure. You can run `python -m nox -s blacken` to format the files, then `python -m nox -s lint` to verify.
(2) unit test failures - `METADATA_HEADERS` instead of `METADATA_HEADER`
(3) after the unit test code is fixed, please run `python -m nox -s cover` to see if all tests and the coverage check can pass (this repo requires 100% code coverage)

Thanks!

2024-04-13 22:09 UTC, arithmetic1728 commented on tests/compute_engine/test__metadata.py
> +        headers=_metadata._METADATA_HEADER,
_METADATA_HEADERS

2024-04-13 22:09 UTC, arithmetic1728 commented on tests/compute_engine/test__metadata.py
> +        headers=_metadata._METADATA_HEADER,
_METADATA_HEADERS

2024-04-13 22:13 UTC, arithmetic1728 commented
Looks like you have an older PR for this as well, https://github.com/googleapis/google-auth-library-python/pull/1481. Should we close that PR?

2026-01-05 17:54 UTC, parthea commented
Closing this PR due to inactivity. Please feel free to re-open it after addressing the feedback

2026-01-05 17:54 UTC, closed without merging